## operation on raspberry pi
# curl -sSL https://get.docker.com | sh
# sudo gpasswd -a pi docker
# sudo mkdir /share
#
# docker build -t samba .
# docker images
# docker run -d -p 139:139 -p 445:445 -v /share:/share samba
### 
# smbuser: samba
# smbuserpw: password
###
FROM centos:7
MAINTAINER you345
RUN yum -y install samba ed
RUN useradd -m -d /samba samba
RUN echo -e 'password\npassword' | pdbedit -a -u samba
RUN echo -e '\
/workgroup\n\
s/SAMBA/WORKGROUP\n\
$\n\
a\n\
[share]\n\
    path = /share\n\
    read only = no\n\
    guest ok = no\n\
    valid users = samba\n\
.\n\
w\n\
q\n' | ed /etc/samba/smb.conf
CMD [ "bash", "-c", "nmbd -D && smbd -F </dev/null" ]
